In [2]:
import pandas as pd
import numpy as np
from sklearn import datasets, linear_model
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import *
from sklearn.model_selection import train_test_split  
import statsmodels.api as sm
from scipy import stats
from statsmodels.stats.outliers_influence import variance_inflation_factor as vif   
import seaborn as sb
from regressors import stats 
from sklearn.preprocessing import StandardScaler   
from sklearn.model_selection import GridSearchCV

In C:\Users\denis\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The text.latex.preview rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\denis\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The mathtext.fallback_to_cm rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\denis\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: Support for setting the 'mathtext.fallback_to_cm' rcParam is deprecated since 3.3 and will be removed two minor releases later; use 'mathtext.fallback : 'cm' instead.
In C:\Users\denis\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The validate_bool_maybe_none function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\denis\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mpl

### 1. Linear Regressions

#### Data:

In [73]:
dcdf = pd.read_excel('ols_complete.xlsx')
X=dcdf.drop('y', axis=1)
y = dcdf['y']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)  

#### Train:

In [74]:
# Create linear regression object
reg1 = linear_model.LinearRegression()

# Train the model using the training sets
reg1.fit(X_train, y_train)
reg1.score(X_train, y_train)
stats.summary(reg1, X_train, y_train)

Residuals:
     Min      1Q  Median    3Q      Max
-14.5136 -1.9975 -0.3284  2.44  20.8646


Coefficients:
             Estimate              Std. Error             t value   p value
_intercept  24.130725      8.789067+0.000000j  2.745500-0.000000j  0.007324
x1          -0.027047      0.210262+0.000000j -0.128600+0.000000j  0.897939
x2           0.048774      0.183080+0.000000j  0.266400-0.000000j  0.790550
x3           0.097032      0.190645-0.000000j  0.509000+0.000000j  0.612050
x4          -0.012660      0.011610+0.000000j -1.090400+0.000000j  0.278494
x5          -0.002056      0.004851+0.000000j -0.423900+0.000000j  0.672707
x6          -0.008769      0.003530-0.000000j -2.483900-0.000000j  0.014888
x7          -0.000009      0.000022-0.000000j -0.401200-0.000000j  0.689219
x8          -0.000027      0.000016-0.000000j -1.727600-0.000000j  0.087569
x9          -0.003566      0.000552-0.000000j -6.453600-0.000000j  0.000000
x10          0.000794  15007.118707-0.000000j  0.000000+0

In [75]:
y_pred = reg1.predict(X_train)
print(reg1.score(X_train, y_train))
print(mean_squared_error(y_train, y_pred))

0.8260090372973465
20.962585825524055


#### Test:

In [76]:
y_pred = reg1.predict(X_test)
print(reg1.score(X_test, y_test))
print(mean_squared_error(y_test, y_pred))
reg1.coef_

0.6140374533341029
24.36985888130216


array([-2.70473329e-02,  4.87737205e-02,  9.70318207e-02, -1.26599255e-02,
       -2.05594902e-03, -8.76870681e-03, -8.76617055e-06, -2.71211944e-05,
       -3.56555519e-03,  7.93608181e-04,  9.47816575e-05,  1.60708421e-03,
       -4.71989343e-03,  4.44243201e-03,  2.05492789e-05, -7.44330400e-03,
       -2.12229037e-03,  1.03592026e-02,  1.11796575e-01, -2.64628611e-02,
       -1.83693329e-03,  8.87864352e-02,  4.97476384e-03, -3.43590112e-03,
        1.68427379e-02, -7.63956219e-03, -4.97366642e-03])

In [79]:
y_pred

array([26.61350855, 47.92576049, 22.33851497, 35.98747086,  8.19157773,
       33.22000131, 36.09467013, 37.76898738, 27.22565069, 33.85887584,
       40.58210719, 36.81546315, 31.19458753, 40.34046738, 36.70176776,
       40.75275402, 31.27006701, 37.64338288, 31.845274  , 38.78840028,
       29.12193355, 43.14945909, 36.8538251 , 50.16076226, 30.99035216,
       44.89977705, 32.40161945, 34.69599187, 33.17443733, 45.46712336,
       31.56621232, 19.52587288, 29.74228979, 44.48011496, 38.06635262,
       37.39588848, 35.0005231 , 35.64232433, 51.16659458, 27.12014377,
       30.03426596, 47.07301297, 28.36335186, 31.86803672, 33.2833207 ,
       35.74829761, 35.22503781, 46.21219071, 31.06260309, 40.44190139,
       29.53631289, 38.66229176, 37.07852613, 35.7919233 , 44.99423798,
       36.67968336, 36.02231993, 28.01776316, 32.06104523, 30.88594727,
       39.6537882 , 31.90204935, 35.71575896, 36.37748878, 67.49905372,
       29.15133126, 36.3738791 , 37.7835352 , 48.04982702, 42.00

In [80]:
y_test.to_excel('ols_test.xlsx')

### 2. Lasso Regressions

#### Data:

In [56]:
dcdf = pd.read_excel('ols_complete_mod03.xlsx')
X=dcdf.drop('y', axis=1)
y = dcdf['y']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)  

#### Train:

In [57]:
alphas = np.linspace(.0001, 2, 1)
param = [{'alpha': alphas}]
lasso = Lasso(random_state=42, max_iter=50000, copy_X=True, normalize=True)
reg_lasso = GridSearchCV(lasso, param, cv = 5)
reg_lasso.fit(X_train, y_train)
print('Lasso best alpha:')
print(reg_lasso.best_params_)
print('R2 score')
print(reg_lasso.score(X_train, y_train))

Lasso best alpha:
{'alpha': 0.0001}
R2 score
0.8263667370291145


C:\Users\denis\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [58]:
lasso_best=Lasso(alpha = 0.0001, random_state=42, max_iter=100000, copy_X=True, normalize=True )
lasso_best.fit(X_train, y_train)
y_pred = lasso_best.predict(X_train)
print('R2 score')
print(lasso_best.score(X_train, y_pred))

R2 score
1.0


In [59]:
mean_squared_error(y_train, y_pred)

12.557036510447904

In [60]:
stats.summary(lasso_best, X_train, y_train)

Residuals:
    Min      1Q  Median     3Q      Max
-13.586 -1.5026 -0.1433  1.397  16.8257


Coefficients:
             Estimate              Std. Error             t value   p value
_intercept  12.533670      6.507182+0.000000j  1.926100-0.000000j  0.057316
x1          -0.024228      0.161000+0.000000j -0.150500+0.000000j  0.880729
x2           0.122442      0.139518+0.000000j  0.877600-0.000000j  0.382545
x3           0.142747      0.144250-0.000000j  0.989600+0.000000j  0.325092
x4          -0.010136      0.008661-0.000000j -1.170300-0.000000j  0.245032
x5          -0.002136      0.003637+0.000000j -0.587400+0.000000j  0.558458
x6          -0.004493      0.002663-0.000000j -1.687100-0.000000j  0.095118
x7          -0.000013      0.000014+0.000001j -0.930500+0.049700j  0.353971
x8          -0.000026      0.000012-0.000000j -2.170400-0.000000j  0.032671
x9          -0.001577      0.000414+0.000000j -3.812400+0.000000j  0.000255
x10         -0.000000  22142.527020+0.000000j  0.000000+0

In [61]:
# Make predictions using the testing set
y_pred = lasso_best.predict(X_test)

len(y_pred)
# The coefficients
print('Coefficients: \n', lasso_best.coef_)
# The mean squared error
print('Mean squared error: %.2f'
      % mean_squared_error(y_test, y_pred))
# The coefficient of determination: 1 is perfect prediction
print('Coefficient of determination: %.2f'
      % r2_score(y_test, y_pred))

Coefficients: 
 [-2.42275243e-02  1.22442368e-01  1.42746993e-01 -1.01357546e-02
 -2.13634923e-03 -4.49346275e-03 -1.34711955e-05 -2.59849681e-05
 -1.57726302e-03 -0.00000000e+00  4.18506111e-05  9.47795548e-03
  1.06153911e-02  2.57542573e-03 -6.13752643e-06 -1.23235382e-02
 -7.70613933e-03  7.12207415e-03  1.37631940e-01 -1.60558699e-02
  4.92436317e-02  2.35060208e-02]
Mean squared error: 15.53
Coefficient of determination: 0.72


### In here the LASSO provide a better estimation and there is a drop for x10 and x15

In [62]:
dcdf = pd.read_excel('ols_complete_mod03_drop1015.xlsx')
X=dcdf.drop('y', axis=1)
y = dcdf['y']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)  

In [63]:
alphas = np.linspace(.0001, 2, 1)
param = [{'alpha': alphas}]
lasso = Lasso(random_state=42, max_iter=50000, copy_X=True, normalize=True)
reg_lasso = GridSearchCV(lasso, param, cv = 5)
reg_lasso.fit(X_train, y_train)
print('Lasso best alpha:')
print(reg_lasso.best_params_)
print('R2 score')
print(reg_lasso.score(X_train, y_train))

Lasso best alpha:
{'alpha': 0.0001}
R2 score
0.8263321316634188


C:\Users\denis\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [64]:
lasso_best=Lasso(alpha = 0.0001, random_state=42, max_iter=100000, copy_X=True, normalize=True )
lasso_best.fit(X_train, y_train)
y_pred = lasso_best.predict(X_train)
print('R2 score')
print(lasso_best.score(X_train, y_pred))

R2 score
1.0


In [65]:
mean_squared_error(y_train, y_pred)

12.559539146366076

In [66]:
stats.summary(lasso_best, X_train, y_train)

Residuals:
     Min      1Q  Median      3Q      Max
-13.5755 -1.4519 -0.0952  1.4287  16.8733


Coefficients:
             Estimate  Std. Error  t value   p value
_intercept  12.494809    6.500298   1.9222  0.057817
x1          -0.026608    0.159788  -0.1665  0.868130
x2           0.122635    0.139467   0.8793  0.381627
x3           0.142852    0.144254   0.9903  0.324750
x4          -0.010130    0.008742  -1.1588  0.249689
x5          -0.001997    0.003580  -0.5579  0.578340
x6          -0.004768    0.001755  -2.7167  0.007938
x7          -0.000015    0.000015  -0.9706  0.334412
x8          -0.000025    0.000012  -2.1367  0.035400
x9          -0.001564    0.000371  -4.2211  0.000059
x10          0.000042    0.000006   6.6270  0.000000
x11          0.009414    0.003287   2.8642  0.005226
x12          0.010736    0.003624   2.9622  0.003928
x13          0.002519    0.001748   1.4407  0.153221
x14         -0.012270    0.002289  -5.3596  0.000001
x15         -0.007648    0.002366  -3.232

In [67]:
# Make predictions using the testing set
y_pred = lasso_best.predict(X_test)

len(y_pred)
# The coefficients
print('Coefficients: \n', lasso_best.coef_)
# The mean squared error
print('Mean squared error: %.2f'
      % mean_squared_error(y_test, y_pred))
# The coefficient of determination: 1 is perfect prediction
print('Coefficient of determination: %.2f'
      % r2_score(y_test, y_pred))

Coefficients: 
 [-2.66077744e-02  1.22634883e-01  1.42852438e-01 -1.01300282e-02
 -1.99744335e-03 -4.76808136e-03 -1.50074296e-05 -2.51152134e-05
 -1.56405957e-03  4.19692147e-05  9.41402419e-03  1.07361125e-02
  2.51857862e-03 -1.22700159e-02 -7.64782699e-03  7.06581736e-03
  1.39764691e-01 -1.41115353e-02  4.81001891e-02  2.09849978e-02]
Mean squared error: 15.55
Coefficient of determination: 0.72


In [68]:
y_pred

array([13.7995867 , 28.74422571,  3.44181174, 19.35504535,  3.58372944,
       22.34608114, 21.98483629, 24.41139473, 15.59039527, 23.15996984,
       24.55323504, 21.09711602, 19.28965563, 25.22775692, 21.58672554,
       23.94179803, 18.61658611, 21.88066542, 16.27051512, 24.6400366 ,
       15.37889363, 29.67583918, 22.84975187, 29.52252909, 14.89433562,
       29.33397929, 16.07716529, 19.24197819, 14.72635815, 25.84768642,
       13.27174217, 10.63696659,  8.99087753, 28.78757237, 25.31116494,
       21.04844211, 19.33930253, 25.68306092, 34.73808897, 15.3944774 ,
       14.61497642, 28.71408046, 10.90065705, 17.80686447, 20.55107709,
       22.93778256, 20.5742696 , 33.30095724, 17.34344979, 23.64303783,
       19.74567818, 23.90933248, 24.27184882, 20.22302067, 27.9892003 ,
       20.77035001, 21.36160545, 12.30481786, 13.81255779, 12.01066242,
       23.69493846, 19.25137851, 23.97439232, 20.8952591 , 45.27594769,
       15.45260708, 23.03178307, 21.77876422, 31.32337082, 26.90

In [69]:
y_test

78     15.59
16     28.36
65     10.85
114    18.37
76     12.43
       ...  
101    15.36
28     29.06
40     48.15
137    23.94
138     9.95
Name: y, Length: 90, dtype: float64

In [70]:
y_pred_train = lasso_best.predict(X_train)
y_pred_train

array([23.29341424, 42.55953237, 11.79921831, 20.93062906,  1.76204876,
       23.25710658, 21.63414139,  1.1347835 , 16.87328653, 20.53998403,
       12.80998866,  7.91655865, 21.5766419 , 13.4698154 , 16.83996985,
       13.62243926, 18.39723086, 18.80540533, 27.45475882, 15.37418764,
       29.65135273, 18.74984022, 18.06857286, 17.61569954, 17.83418133,
       29.58591124, 24.37608742, 23.58599602, 22.35214991, 23.59897873,
       33.48725926, 16.72536945, 27.60466702, 29.12268011, 12.55396205,
       14.78189999, 20.61013221, 17.18913426, 33.14746764, 19.58285445,
       34.71446854, 31.25946238, 12.62682284, 23.75457282, 17.65441663,
       20.9933495 , 38.06068875, 25.26315353, 17.61238266, 14.85168927,
       26.00550547,  9.26891124, 14.50372445, 15.59385301, 24.93406618,
       17.81809596, 24.44810399, 12.97085912, 11.18608919, 28.19264747,
       11.20543671, 20.89632034, 22.41348017, 24.74951761, 27.81963517,
       23.4468975 , 22.00645122, 20.19246042, 28.40590232, 15.96

In [71]:
y_train

25     25.55
23     39.74
133    13.20
81     23.93
79      0.00
       ...  
71     24.83
106    15.41
14     34.58
92     13.48
102    15.51
Name: y, Length: 89, dtype: float64

### 3. Ridge Regressions

In [81]:
dcdf = pd.read_excel('ols_complete.xlsx')
X=dcdf.drop('y', axis=1)
y = dcdf['y']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)  

In [82]:
alphas = np.linspace(.0001, 2, 1)
param = [{'alpha': alphas}]
ridge = Ridge(random_state=42, max_iter=50000, copy_X=True, normalize=True)
reg_ridge = GridSearchCV(ridge, param, cv = 5)
reg_ridge.fit(X_train, y_train)
print('Ridge best alpha:')
print(reg_ridge.best_params_)
print('R2 score')
print(reg_ridge.score(X_train, y_train))

Ridge best alpha:
{'alpha': 0.0001}
R2 score
0.8260088746076494


C:\Users\denis\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [83]:
ridge_best=Ridge(alpha = 0.01, random_state=42, max_iter=100000, copy_X=True, normalize=True )
ridge_best.fit(X_train, y_train)
y_pred = ridge_best.predict(X_train)
print('R2 score')
print(ridge_best.score(X_train, y_pred))

R2 score
1.0


In [84]:
mean_squared_error(y_train, y_pred)

21.043664583695193

In [85]:
stats.summary(ridge_best, X_train, y_train)

Residuals:
     Min      1Q  Median      3Q      Max
-15.1943 -2.1406 -0.1205  2.3538  21.5255


Coefficients:
             Estimate              Std. Error             t value   p value
_intercept  23.338721      8.806048-0.000000j  2.650300+0.000000j  0.009535
x1          -0.018982      0.210668-0.000000j -0.090100-0.000000j  0.928411
x2           0.068335      0.183433-0.000000j  0.372500+0.000000j  0.710390
x3           0.085249      0.191013-0.000000j  0.446300+0.000000j  0.656476
x4          -0.010194      0.011632+0.000000j -0.876300+0.000000j  0.383240
x5          -0.001872      0.004861-0.000000j -0.385100-0.000000j  0.701065
x6          -0.008345      0.003537+0.000000j -2.359400+0.000000j  0.020519
x7          -0.000005      0.000020+0.000000j -0.236000+0.000000j  0.813978
x8          -0.000031      0.000016+0.000000j -1.999000+0.000000j  0.048693
x9          -0.003393      0.000545-0.000000j -6.223300-0.000000j  0.000000
x10          0.000127  15036.112812+0.000000j  0.0000

In [86]:
# Make predictions using the testing set
y_pred = ridge_best.predict(X_test)

len(y_pred)
# The coefficients
print('Coefficients: \n', ridge_best.coef_)
# The mean squared error
print('Mean squared error: %.2f'
      % mean_squared_error(y_test, y_pred))
# The coefficient of determination: 1 is perfect prediction
print('Coefficient of determination: %.2f'
      % r2_score(y_test, y_pred))

Coefficients: 
 [-1.89815422e-02  6.83354808e-02  8.52493508e-02 -1.01936638e-02
 -1.87225416e-03 -8.34457969e-03 -4.70083691e-06 -3.10986000e-05
 -3.39294388e-03  1.27030584e-04  9.03850789e-05  1.82653118e-03
 -2.26081768e-04  3.36170385e-03  2.06932148e-05 -4.13075094e-03
  9.18266960e-04  1.18418126e-02  1.23228372e-01 -1.75516197e-02
  3.82056775e-02  8.81552186e-02  7.87444297e-03 -5.13535032e-03
  1.09536247e-02 -1.04385890e-02 -7.35063194e-03]
Mean squared error: 22.55
Coefficient of determination: 0.64


In [87]:
y_pred

array([26.64744034, 48.36057542, 22.76643121, 36.18326236,  9.08900236,
       33.04142449, 36.32505982, 38.46546128, 28.07200385, 34.20825986,
       40.57387632, 37.17858674, 31.44142701, 40.74089637, 36.38350693,
       40.33833321, 31.52584234, 37.09451401, 31.69582349, 39.01176096,
       30.0988383 , 43.0949638 , 36.45968845, 49.73025192, 30.72816999,
       44.81079229, 32.42036453, 34.9976069 , 33.13022456, 45.02779532,
       31.55183117, 19.92633988, 29.68220081, 43.95994769, 38.31634467,
       38.03155557, 34.75484053, 36.66152938, 50.75202014, 27.79415678,
       30.41544425, 46.85850966, 28.45032405, 31.37572681, 33.86055361,
       35.58455841, 35.67830071, 46.07659567, 31.16498503, 39.50529245,
       29.25001152, 38.49844761, 37.0953295 , 36.05462078, 44.61666103,
       36.13096651, 36.47546113, 28.21871266, 32.05253681, 29.86109374,
       39.17044867, 31.62588542, 36.05517326, 36.8192289 , 67.24375903,
       28.90539211, 36.41629182, 37.17016112, 47.43552601, 42.07